<?php
$canRefundPerrmission = Mage::helper('webpos/permission')->canRefund();
$_collection = $this->getOrder();
$i = 0;
$currentDate = Mage::getModel('webpos/session')->getData('currentDate');
$startGroup = false;
foreach ($_collection as $_order): $i++;
    $incrementId = $_order->getIncrementId();
    $orderId = $_order->getId();
    $printLink = $this->getUrl('webpos/order/print', array('order_id' => $orderId, '_forced_secure' => $this->getRequest()->isSecure()));
    $create_time = Mage::helper('core')->formatTime($_order->getCreatedAt(), Mage_Core_Model_Locale::FORMAT_TYPE_SHORT, false);
    $create_date = Mage::app()->getLocale()->date(strtotime($_order->getData('created_at')), null, null, false)->toString('d:M:Y');
    $create_at = Mage::helper('core')->formatDate($_order->getCreatedAt(), Mage_Core_Model_Locale::FORMAT_TYPE_LONG, false);
    if ($currentDate != $create_date) {
        $currentDate = $create_date;
        $startGroup = true;
    } else
        $startGroup = false;
    $grand_total = Mage::helper('core')->currency($_order->getData('base_grand_total'), true, false);
    $total_due = Mage::helper('core')->currency($_order->getBaseTotalDue(), true, false);
    $statusOrderClass = '';
    $orderStatus = $_order->getStatus();
    $orderStatusLabel = $_order->getStatusLabel();
    $canCancel = ($_order->canCancel()) ? 'true' : 'false';
    $canShip = ($_order->canShip()) ? 'true' : 'false';
    $canRefund = ($_order->canCreditmemo() && $canRefundPerrmission == true) ? 'true' : 'false';
    $userId = Mage::helper('webpos/permission')->getCurrentUser();
    $canManageOrder = Mage::helper('webpos/permission')->canManageOrder($userId, $_order->getId());
    if ($canManageOrder == false) {
        $showLabel = 'false';
    } else {
        $showLabel = '';
    }
    $allInvoiceIds = array();
    $invoices = Mage::getResourceModel('sales/order_invoice_collection')
            ->setOrderFilter($_order->getId())
            ->load();
    if (count($invoices) > 0)
        foreach ($invoices as $invoice) {
            $allInvoiceIds[] = $invoice->getId();
        }
    switch ($orderStatus) {
        case "canceled":
            $statusOrderClass = 'type2';
            break;
        case "closed":
            $statusOrderClass = 'type2';
            break;
        case "pending":
            $statusOrderClass = 'type4';
            break;
        case "pending_payment":
            $statusOrderClass = 'type4';
            break;
        case "complete":
            $statusOrderClass = 'type1';
            break;
        case "processing":
            $statusOrderClass = 'type3';
            break;
    }
    $url = $this->getUrl('webpos/index/printInvoice', array('order_id' => $orderId, '_forced_secure' => $this->getRequest()->isSecure()));
    $skus = '';
    $items = $_order->getAllVisibleItems();
    if (count($items) > 0) {
        $numberItems = count($items);
        $index = 1;
        foreach ($items as $item) {
            if ($index == $numberItems)
                $skus .= $item->getSku();
            else
                $skus .= $item->getSku() . ', ';
            $index++;
        }
    }
    ?>
    <div class="form-row">
    <?php if ($startGroup): ?>
            <div class="create-at">
                <div class="date col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <?php echo $create_at; ?>
                </div>
            </div>
            <div class="clear"></div>
    <?php endif; ?>
        <div class="orderlist_item_wrapper">
            <div invoiceId="<?php echo (isset($allInvoiceIds[0])) ? $allInvoiceIds[0] : 'null'; ?>" canInvoice ="<?php echo $canInvoice; ?>" canRefund ="<?php echo $canRefund; ?>" canCancel="<?php echo $canCancel; ?>" canShip="<?php echo $canShip; ?>" printLink="<?php echo $printLink; ?>" increment_id="<?php echo '#' . $incrementId; ?>" created_at="<?php echo $create_at; ?>" grand_total="<?php echo $grand_total; ?>" status="<?php echo $orderStatus; ?>" show_label="<?php echo $showLabel ?>" status_label="<?php echo $orderStatusLabel; ?>" total_due="<?php echo $total_due; ?>" id='orderlist_row_<?php echo $_order->getId(); ?>' class="info <?php echo $statusOrderClass; ?> col-lg-12 col-md-12 col-sm-12 col-xs-12" onclick="showOrder('<?php echo $_order->getId() ?>', '');
                    return false;">
                <ul class="line1">
                    <li class="order-id col-lg-6 col-md-6 col-sm-6 col-xs-6">#<?php echo $incrementId ?></li>
                    <li class="price col-lg-6 col-md-6 col-sm-6 col-xs-6"><?php echo $grand_total; ?></li>
                </ul>
                <ul>
                    <li class="order-id col-lg-6 col-md-6 col-sm-6 col-xs-6"><?php echo $_order->getCustomerName(); ?></li>
                    <li class="price col-lg-6 col-md-6 col-sm-6 col-xs-6"><?php echo $create_time; ?></li>
                </ul>
                <ul class="building-address">
                    <li class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <?php echo $skus; ?>
                    </li>

                </ul>
            </div>
            <button class="bt_reload_order_items btn btn-warning" onclick="reloadOrderItems('<?php echo $orderId; ?>')"><?php echo $this->__('Load items'); ?></button>
        </div>
    </div>
<?php endforeach ?>
<input type="text" id="current_page_number" style="display: none;"/> <!-- Mr.Jack current page -->