<?php
$items = $this->getData('items');
if ($items && count($items) > 0):
    $orderId = $this->getData('order_id');
    ?>
    <table id='items_to_ship_table' class="table table-striped" style='margin-bottom:5px;'>
        <thead>
            <tr>
                <th><?php echo $this->__('Product'); ?></th>
                <th><?php echo $this->__('Sku'); ?></th>
                <th class="text-center"><?php echo $this->__('Qty Ordered'); ?></th>
                <?php if ($orderId != null): ?>
                    <th class="text-center"><?php echo $this->__('Shipped'); ?></th>
                    <th class="text-center"><?php echo $this->__('Refunded'); ?></th>
                    <th class="text-center"><?php echo $this->__('Canceled'); ?></th>
                <?php endif; ?>
                <th class="text-center"><?php echo $this->__('Qty to Ship'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($items as $item):
                if ($item->getData('is_virtual') == true) {
                    continue;
                }
                $orderId = $item->getData('order_id');
                $is_qty_decimal = $item->getData('is_qty_decimal');
                $qty = ($orderId != null) ? $item->getData('qty_ordered') : $item->getData('qty');
                $qty_shipped = ($orderId != null) ? $item->getData('qty_shipped') : 0;
                $qty_refunded = ($orderId != null) ? $item->getData('qty_refunded') : 0;
                $qty_canceled = ($orderId != null) ? $item->getData('qty_canceled') : 0;
                $available_to_ship = $qty - $qty_shipped - $qty_refunded - $qty_canceled;
                if ($is_qty_decimal == false) {
                    $qty = (int) $qty;
                    $qty_shipped = (int) $qty_shipped;
                    $qty_refunded = (int) $qty_refunded;
                    $qty_canceled = (int) $qty_canceled;
                    $available_to_ship = (int) $available_to_ship;
                }
                $item_input_class = ($orderId != null) ? 'order_item_to_ship' : 'item_to_ship';
                ?>
                <tr>
                    <td><?php echo $item->getData('name'); ?></td>
                    <td><?php echo $item->getData('sku'); ?></td>
                    <td class="text-center"><?php echo $qty; ?></td>
                    <?php if ($orderId != null): ?>
                        <td class="text-center"><?php echo $qty_shipped; ?></td>
                        <td class="text-center"><?php echo $qty_refunded; ?></td>
                        <td class="text-center"><?php echo $qty_canceled; ?></td>
                    <?php endif; ?>
                    <td style='width: 10%;' class="text-center"><input <?php if ($available_to_ship == 0) echo "disabled"; ?> order_id="<?php echo $orderId; ?>" onchange="checkItemQtyToShip(this,<?php echo $available_to_ship; ?>)" onclick="this.select()" class='form-control text-center <?php echo $item_input_class; ?>' itemid="<?php echo $item->getData('item_id'); ?>" value="<?php echo $available_to_ship; ?>" /></td>
                </tr>
                <?php
            endforeach;
            ?>
        </tbody>
    </table>
<?php endif; ?>