<?php 
    $_source    = $this->getSource();
    $_order     = $this->getOrder();
    $_fullInfo  = $this->getFullTaxInfo();
?>

<?php if ($this->displayFullSummary()): ?>
    <?php $isTop = 1; ?>
    <?php if(count($_fullInfo) > 0) foreach ($_fullInfo as $info): ?>
        <?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
        <?php 
			if(isset($info['percent']))
				$percent      = $info['percent'];
			if(isset($info['amount']))
				$amount       = $info['amount'];
			if(isset($info['base_amount']))
				$baseAmount   = $info['base_amount'];
			if(isset($info['rates']))
				$rates        = $info['rates'];
            $isFirst      = 1;
        ?>

        <?php if(count($rates) > 0) foreach ($rates as $rate): ?>
        <tr class="tax-details<?php if ($isTop): echo ' tax-details-first'; endif; ?>" style="display:none;">
            <?php if (isset($rate['percent'])): ?>
                <td class="label"><?php echo $rate['title']; ?> (<?php echo $rate['percent']; ?>%)<br /></td>
            <?php else: ?>
                <td class="label"><?php echo $rate['title']; ?><br /></td>
            <?php endif; ?>
            <?php if ($isFirst): ?>
                <td rowspan="<?php echo count($rates); ?>"><?php echo $this->displayAmount($amount, $baseAmount); ?></td>
            <?php endif; ?>
        </tr>
        <?php
            $isFirst = 0;
            $isTop = 0;
        ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
<?php endif;?>
<?php if ($this->displayFullSummary() && $_fullInfo): ?>
<tr class="tax-total" onclick="expandDetails(this, '.tax-details')">
<?php else: ?>
<tr>
<?php endif; ?>
    <td class="label">
        <div class="tax-collapse">
        <?php if ($this->helper('tax')->displayFullSummary()): ?>
            <?php echo Mage::helper('sales')->__('Total Tax') ?>
        <?php else: ?>
            <?php echo Mage::helper('sales')->__('Tax') ?>
        <?php endif;?>
        </div>
    </td>
    <td>
        <?php echo  Mage::helper('core')->currency ($_source->getBaseTaxAmount()); ?>
    </td>
</tr>