
<table cellspacing="0" width="100%">
    <col />
    <col width="1" />
    <?php $_totals = $this->getTotals('footer')?>   
    <?php if ($_totals):?>
    <tfoot>
    <?php foreach ($this->getTotals('footer') as $_code => $_total): ?>
        <?php if ($_total->getBlockName()): ?>
            <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
        <?php else:?>
        <tr class="<?php echo $_code?>">
            <td <?php echo $this->getLabelProperties()?> class="label">
                <strong><?php echo $this->escapeHtml($_total->getLabel()); ?></strong>
            </td>
            <td <?php echo $this->getValueProperties()?> class="emph">
                <strong><?php echo Mage::helper('core')->currency($_total->getBaseValue(),true, false);?></strong>
            </td>
        </tr>
        <?php endif?>
    <?php endforeach?>
    </tfoot>
    <?php endif?>

    <?php $_totals = $this->getTotals('')?>
    <?php if ($_totals):?>
    <tbody>
    <?php
    $arr_totals = array();
    $arr_flag = array();
    foreach ($_totals as $_total){
        if ($_total->getBlockName()){
            $arr_totals[] = $_total;
        } else {
            $arr_flag[] = $_total;
        }
    }

    if(sizeof($arr_flag) > 0){
        foreach ($arr_flag as $flag)
            array_push($arr_totals,$flag);
    }

    foreach ($arr_totals as $_code => $_total): ?>
        <?php if ($_total->getBlockName()): ?>
            <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
        <?php else:?>
        <tr class="<?php echo $_code?>">
            <td <?php echo $this->getLabelProperties()?> class="label">
                <?php if ($_total->getStrong()):?>
                <strong><?php echo $this->escapeHtml($_total->getLabel()); ?></strong>
                <?php else:?>
                <?php echo $this->escapeHtml($_total->getLabel()); ?>
                <?php endif?>
            </td>

            <?php if ($_total->getStrong()){?>
            <td <?php echo $this->getValueProperties()?> class="emph">
                <strong><?php echo  Mage::helper('core')->currency($_total->getBaseValue(),true, false); ?></strong>

			<?php }elseif ($_total->getCode() == 'rewardpoints_earn_label'){?>
            <td <?php echo $this->getValueProperties()?> class="emph">
                <strong><?php echo  $_total->getBaseValue(); ?></strong>
            <?php }else{?>
            <td <?php echo $this->getValueProperties()?>>
                <?php echo  Mage::helper('core')->currency($_total->getBaseValue(),true, false);  ?>

            <?php } ?>
            </td>
        </tr>
        <?php endif?>
    <?php endforeach?>
    </tbody>
    <?php endif?>
</table>
