<?php if($this->getCurrencyCount()>1): ?>
<div class="webpos_currency">
	<select name="currency" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Select Your Currency')) ?>" onchange="changeCurrency(this)">
	<?php foreach ($this->getCurrencies() as $_code => $_name): ?>
		<option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
			<?php echo $_name ?> - <?php echo $_code ?>
		</option>
	<?php endforeach; ?>
	</select>
</div>

<script type='text/javascript'>
function changeCurrency(el){
	if(typeof el != 'undefined' && el.value != null){
		localSet('changedCurrency','ok');
		setLocation(el.value);
	}
}
$D(document).ready(function(){
	var changedCurrency = localGet('changedCurrency');
	if(changedCurrency != null && typeof changedCurrency != 'undefined' && changedCurrency == 'ok'){
		localDelete('changedCurrency');	
		if(useLocalSearch == true){
			flushProductCache();
		}else{ 
			reloadListProduct('category', '0', '<?php echo $this->__('All Categories');?>');
		
		}
	}
});

</script>
<?php endif; ?>
