<!--S: Daniel - updated 10/10/2016 - new multipayment calculation -->
<script>
    if(MultiPaymentManagement){
        MultiPaymentManagement.init({
            label:{
                'remaining' : '<?php echo $this->__('Remain money');?>',
                'change' : '<?php echo $this->__('Expected Change');?>',
                'partial' : '<?php echo $this->__('Mark As Partial');?>',
                'placeOrder' : '<?php echo $this->__('Place Order');?>'
            }
        });
    }
</script>
<!--E: Daniel - updated 10/10/2016 - new multipayment calculation -->