<style type='text/css'>
    .product_list .product .product_options{
        max-height: 72vh;
        overflow: hidden;
    }
    .product_list .product .product_options .col-value ul{
        overflow: auto;
        max-height: 57vh;
    }
    #popup-customer ul{
        overflow-x: hidden !important;
        overflow-y: auto !important;
    }
	.ui-widget-header,
    .footer #cancel-sale-btn button:hover,
    .discount-webpos .discount-type button.btn2, 
    .discount-webpos .choose-discount .btn2, 
    .custom_price_tab .discount-type .btn2,
    .discount-webpos .top-title,
    #edit_cart_item_popup .product_tab .common .choose,
    .custom_price_tab .custom-price button,
    #bt_remove_tax,
    #count_cash_area button,
    #current_balance_line,
    .webpos_popup_area .top_content .popup_title,
    #holded_orders_section .content .item .bt_reload_order,
    #holded_orders_section .content .item .bt_delete_holded_order,
    #bt_hold_order,
    #reports_area button,
    #cashdrawer_area button,
    #reports_area .top-content .title-page,
    #cashdrawer_area .top-content .title-page,
    #holded_orders_detail .top-content .title-page,
    #holded_orders_section .top-content .title-page,
    #pending_orders_popup .panel-heading,
    #order-success button.new-order,
    #orders_area #orderlist-search-form,
    #create-customer .modal-content .top-create, #shipping-address .modal-content .top-create,
    #popup-customer button,
    .product_list .product .product_options ul .product-name h2,
    .btn-warning,
    #order_info .checkout_buttons_area button.btn-warning,
    #shipping_area #edit_shipping_address,
    #settings_area .top-content,
    #orders_area .order-detail .send-email .top-form, #orders_area .order-detail .refund .top-form,
    #orders_area .form-search,
    #orders_area .order-detail .top-order .head-view-order,
    .top_bar.left,
    #pos_container #main_container .col_right .top_bar,
    #bt_checkout
    {
        <?php
        $storeId = Mage::app()->getStore()->getId();
        $webpos_color = str_replace('#', '', Mage::getStoreConfig('webpos/general/webpos_color', $storeId));
        if (isset($webpos_color) && $webpos_color != '') {
            echo "background:#" . $webpos_color . " !important;";
            echo "border-color:#" . $webpos_color . " !important;";
        }
        ?> 
    }
    #selectcategory{
        border: 2px solid rgba(0, 0, 0, 0.1) !important;
    }
    #current_balance_line .balance_wrapper .current_balance_fake{
        <?php
        if (isset($webpos_color) && $webpos_color != '') {
            echo "color:#" . $webpos_color . " !important;";
        }
        ?> 
    }
    .zopim,
    .mobile_menu,
    .snap-drawers,
    #after-loading-success-message,
    #dp_swf_engine,
    #after-loading-success-message,
    #loading-mask
    {
        display: none !important;
    }

    #total_wp strong{
        line-height: 50px;
        padding-left: 15px;
    }

    #total_wp #grand_total_wp_show_hide strong {
        line-height: initial;
        padding-left: initial;
    }

</style>
<style type='text/css' id='css_from_js'>

</style>
<script type='text/javascript'>
    var check = false;
//$D(document).ready(function(){
    var styles = $$('link');
    if (styles.length > 0) {
        styles.each(function(el) {
            var href = el.getAttribute('href');
            if (href != '' && href != null) {
                if (href.indexOf('webpos') < 0 && href.indexOf('bookmepro_calendar') < 0)
                    el.remove();
            }
        })
    }
    var main_containers = $$('.wrapper .page .main-container .container');
    if (main_containers.length > 0) {
        main_containers.each(function(el) {
            el.removeClassName('container');
        });
    }
    var containers = $$('.wrapper .page .main-container');
    if (containers.length > 0) {
        containers.each(function(el) {
            el.removeClassName('main-container');
        });
    }
//});

    function removeUnnecessary() {
        var testimonials = $$('.testimonials');
        if (testimonials.length > 0) {
            check = false;
            testimonials.each(function(el) {
                el.remove();
            });
        } else {
            check = true;
        }
        var zopim = $$('.zopim');
        if (zopim.length > 0) {
            check = false;
            zopim.each(function(el) {
                el.remove();
            });
        } else {
            check = true;
        }
    }
</script>

<div class="webpos_overlay" id="webpos_number_board_overlay" onclick="hideNumberBoard()" style='display:none;'></div>
<div id='webpos_number_board' class="form-group webpos_number_board" currentInput=''>
    <ul>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="1">1</button>
        </li>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="2">2</button>
        </li>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="3">3</button>
        </li>
    </ul>        
    <ul>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="4">4</button>
        </li>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="5">5</button>
        </li>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="6">6</button>
        </li>
    </ul>
    <ul>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="7">7</button>
        </li>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="8">8</button>
        </li>
        <li class="col-lg-4 col-md-4  col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="9">9</button>
        </li>
    </ul>
    <ul>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput decimalSymbol" value=".">.</button>
        </li>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="0">0</button>
        </li>
        <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
            <button type="button" class="btn btn-default numberInput" value="00">00</button>
        </li>        
    </ul>
    <ul>
        <li class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <button type="button" class="btn btn-default clear-number" ></button>
        </li>  
    </ul>
</div>
<input type='hidden' id='webpos_number_board_default_input'/>
<script type='text/javascript'>
    var numberBoard = new webposNumberBoard('webpos_number_board_default_input', '50%', '150vh');
    numberBoard.hideBoard();
</script>

<div id='splitship_area' class='webpos_popup_area' style='display:none;'>
    <div class='webpos_popup_loader' style="display: none;">
        <div class="img-ajax"></div>
    </div>
    <div class="top_content">
        <div class="popup_title">
            <h2><?php echo $this->__('Items to Ship'); ?></h2>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <div class='popup_content'>

    </div>
    <div class='bottom_buttons'>
        <div class='track_number_form col-lg-10 col-md-10 col-sm-10 col-xs-10'><label class="col-lg-5 col-md-5 col-sm-5 col-xs-5"><?php echo $this->__('Track Number');?></label><input class='col-lg-5 col-md-5 col-sm-5 col-xs-5' id='track_number'/></div>
        <button type="button" class="btn btn-default btn-back" onclick="hideSplitshipPopup()"><?php echo $this->__('Cancel'); ?></button>
        <button type="button" class="btn btn-default btn-next" onclick="selectedItemsToShip()"><?php echo $this->__('Done'); ?></button>
    </div>
</div>
<script type='text/javascript'>
    var splitShipPopup = new webposPopup('splitship_area', 'webpos_fixed_overlay', []);
    splitShipPopup.hideBoard();
</script>