<?php
$quote = Mage::getModel('checkout/cart')->getQuote();
$grandTotal = $quote->getGrandTotal();

//$downgrandtotal = ($grandTotal % 50 == 0) ? $grandTotal : floor($grandTotal - $grandTotal % 50);
//$upgrandtotal = ($grandTotal % 50 == 0) ? $grandTotal : floor($grandTotal - $grandTotal % 50 + 50);
$downgrandtotal = Mage::helper('webpos')->round_down_cashin($grandTotal);
$upgrandtotal = Mage::helper('webpos')->round_up_cashin($grandTotal);
$currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
?>
<div id="order_info_wp">
    <div id='shipping_payment_wrapper' class="">
        <div class='shipping_payment_area'>
            <div class='shipping'>
                <div class="pospanel" id='shipping_area'>
                    <div id='edit_shipping_address' onclick="showEditAddress()"><?php echo $this->__('Edit address'); ?></div>
                    <div onclick="shippingHeaderClick()" class="panel-heading"><?php echo $this->__('Shipping'); ?>
                    </div>
                    <div class="panel-body hidding">
                        <form id='webpos_shipping_method_form'>
                            <div id='shipping_method'>
                                <?php echo $this->getChildHtml('webpos_shipping_method'); ?>
                            </div>
                        </form>
                        <div id='address'>
                        </div>
                    </div>
                </div>

            </div>
            <div class='payment'>
                <div class="pospanel" id='payment_area'>
                    <div onclick="paymentHeaderClick()" class="panel-heading"><?php echo $this->__('Payment'); ?>
                        <div class="payment-remain-info">
                            <label id="remaining_label"><?php echo $this->__('Remaining'); ?></label>
                            <span id="remaining_amount"><?php echo Mage::app()->getStore()->formatPrice($grandTotal); ?></span>
                        </div>
                    </div>
                    <div class="panel-body">

                        <form id='webpos_payment_method_form'>
                            <div class="hide" id="cash_remain">
                                <div class="">
                                    <div class="text-right col-lg-8 col-md-8 col-sm-8 col-xs-8"><span><?php echo $this->__('Amount Tendered: '); ?></span></div>
                                    <div class="text-right col-lg-4 col-md-4 col-sm-4 col-xs-4"><span id='cashin_value_label'><?php echo '0' ?></span></div>
                                </div>
                                <div class="">
                                    <div class="text-right col-lg-8 col-md-8 col-sm-8 col-xs-8"><span><?php echo $this->__('Remaining: '); ?></span></div>
                                    <div class="text-right col-lg-4 col-md-4 col-sm-4 col-xs-4"><span id='remain_value_label'><?php echo Mage::app()->getStore()->formatPrice($quote->getGrandTotal()); ?></span></div>
                                </div>
                                <div class='clear'></div>
                            </div>
                            <div id='payment_method'>
                                <?php echo $this->getChildHtml('webpos_payment_method'); ?>
                            </div>

                        </form>                            
                        <div class="form-cashin" id="form-cashin">                                 
                            <div class="form-group">
                                <div class="text-right col-lg-8 col-md-8 col-sm-8 col-xs-8"><span><?php echo $this->__('Amount Tendered: '); ?></span></div>
                                <div class="text-right col-lg-4 col-md-4 col-sm-4 col-xs-4"><input onkeydown ="keyCheck(event);
                                        if (event.keyCode == 8 || event.keyCode == 46)
                                            return false;" onchange="calculateRemain()" onkeypress="formatInputPrice(event);
                                                    return false" type="text" placeholder="<?php echo Mage::helper('core')->currency(0, true, false); ?>" id="cashin_value" class="" value='' currencySymbol="<?php echo $currencySymbol; ?>"/></div>
                            </div>
                            <div class="form-group">
                                <div class="text-right col-lg-8 col-md-8 col-sm-8 col-xs-8"><span><?php echo $this->__('Remain: '); ?></span></div>
                                <div class="text-right col-lg-4 col-md-4 col-sm-4 col-xs-4"><span id='remain_value'><?php echo Mage::app()->getStore()->formatPrice($quote->getGrandTotal()); ?></span></div>
                            </div>
                            <div class="form-group">
                                <ul>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default btn-warning" id='round_down_cashin' onclick="applyCashin(this)"><?php echo Mage::app()->getStore()->formatPrice($downgrandtotal); ?></button>
                                    </li>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default btn-warning" id='cashin_fullamount' onclick="applyCashin(this)"><?php echo Mage::app()->getStore()->formatPrice($quote->getGrandTotal()); ?></button>
                                    </li>

                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default btn-warning" id='round_up_cashin' onclick="applyCashin(this)"><?php echo Mage::app()->getStore()->formatPrice($upgrandtotal); ?></button>
                                    </li>
                                </ul>     
                                <ul>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="1">1</button>
                                    </li>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="2">2</button>
                                    </li>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="3">3</button>
                                    </li>
                                </ul>        
                                <ul>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="4">4</button>
                                    </li>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="5">5</button>
                                    </li>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="6">6</button>
                                    </li>
                                </ul>
                                <ul>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="7">7</button>
                                    </li>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="8">8</button>
                                    </li>
                                    <li class="col-lg-4 col-md-4  col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="9">9</button>
                                    </li>
                                </ul>
                                <ul>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button id="delete_cashin" type="button" class="btn btn-default clear-number numberInput" ></button>
                                    </li>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="0">0</button>
                                    </li>
                                    <li class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <button type="button" class="btn btn-default numberInput" value="00">00</button>
                                    </li>        
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class='checkout_buttons_area'>
            <div id="options_after_place_order">
                <div class='option check_shipment'>
                    <ul>
                        <li>
                            <label class="shipping-order"><?php echo $this->__('Create shipment?') ?></label>
                            <input id='create_shipment' type="checkbox" checked data-toggle="toggle" class="input-text check-shipping"/>
                        </li>
                    </ul>
                </div>
                <div class='option show' id="create_invoice_container">
                    <ul>
                        <li>
                            <label class="shipping-order"><?php echo $this->__('Create invoice?') ?></label>
                            <input id='create_invoice' type="checkbox" checked   data-toggle="toggle" class="input-text check-shipping"/>
                        </li>
                    </ul>
                </div>
            </div>
            <!--div class='col-lg-6 col-md-6 col-sm-6 col-xs-6'>
                <button type="button" class="btn btn-default" id='bt_cashin' onclick="showCashIn()"><?php echo $this->__('Amount Tendered'); ?></button>
            </div-->
            <div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
                <button type="button" class="btn btn-warning" id='bt_place_order' onclick="webposPlaceOrder(place_order_url)"><?php echo $this->__('Place Order'); ?></button>
            </div>
        </div>
    </div>
    <div class="order-success hide" id="order-success">
        <h2 class="price-order" id='success_orderGrandTotal'></h2>
        <div class="check-order">
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"  style="padding:0"><img src='<?php echo $this->getSkinUrl('images/icon/check_order.png'); ?>' /></div>
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" style="padding:0">
                <p><?php echo $this->__('Order has been created successfully'); ?></p>
                <p><?php echo $this->__('Order ID:'); ?> <span id='success_orderIncrementId'></span></p>   
            </div>        
        </div>
        <!--    <div class="check-invoice">
                <p>Order fulfillment</p>
                <p>Invoice ID: #</p>
            </div>-->
        <form action="">
            <input type="hidden" id='success_order_id' value=''/>

            <div class="form-order" >
                <input type="text" id='success_customerEmail' class="input-text form-control email" placeholder="<?php echo $this->__('Email Address'); ?>"/>
                <button type="button" class="btn btn-warning" onclick="sendOrderToCustomerViaEmail()"><?php echo $this->__('Send'); ?></button>
            </div>
            <button type="button" class="btn btn-default print" id='success_print'><?php echo $this->__('Print Receipt'); ?></button>
        </form>

        <button type="button" class="btn btn-warning new-order"  onclick="applyOptionsAfterPlaceOrder()"><?php echo $this->__('Start New Order'); ?></button>
    </div>
</div>
<script type="text/javascript">
    /*Mr.Jack calculate custom sale*/
    var symbolCash = "<?php echo $currencySymbol; ?>";
    function keyCheck(event)
    {
        var KeyID = event.keyCode;
        switch (KeyID)
        {
            case 8:
                $('delete_cashin').click();
                break;
            default:
                break;
        }
    }

    function numberWithCommas(price) {
        price = price.toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,');
        return price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
    }
    var countCashin = 0;
    var hisCustomCashin = [""];
    function formatInputPrice(event) {
        var keyValue = String.fromCharCode(event.which);
        var keyCode = event.which || event.keyCode;
        $$('.form-cashin .form-group ul li .numberInput').each(function(element) {
            if (element.value == keyValue)
                element.click();
        });
    }
    $$('.form-cashin .form-group ul li .numberInput').each(function(element) {
        element.observe("click", function(event) {
            if (element.id != 'delete_cashin') {
                countCashin++;
                hisCustomCashin[countCashin] = hisCustomCashin[countCashin - 1] + element.value;
            }
            else {
                if (hisCustomCashin.length > 1)
                    hisCustomCashin.pop();
                if (countCashin >= 1)
                    countCashin--;
            }
            if (typeof hisCustomCashin[countCashin] != "undefined") {
                if (!hisCustomCashin[countCashin])
                    hisCustomCashin[countCashin] = 0;
                if (hisCustomCashin[countCashin] != 0) {
                    $('cashin_value').value = formatCurrency(parseInt(hisCustomCashin[hisCustomCashin.length - 1]) / 100, priceFormat, false);
                }
                else
                    $('cashin_value').value = '';
                calculateRemain();
            }
            /*disabled place order button if doesn't pay by full amount Mr.Jack*/
            canPlaceOrder();
        });
    });
    canPlaceOrder();
</script>