<?php    $slide_status=$this->getResponsivebannersliderEnabled();   ?>
<?php    $slide_speed=$this->getResponsivebannersliderSpeed();   ?>
<?php    $slide_type=$this->getResponsivebannerSlideType(); ?>
<?php    $slide_BannerLoop=$this->getResponsivebannerBannerLoop(); ?>
<?php    $slide_PauseOnhover=$this->getResponsivebannerPauseOnhover(); ?>


<?php
// Module Enable/Dsable Function.......................................
if($slide_status==1){ ?>



<?php
// Module type Function.......................................
if($slide_type=='1'){ ?> 

	<?php  $cssurl =  str_replace('index.php/','',$this->getUrl());?>  
	<div class="the-slideshow-wrapper nested-container clearer">
	<div style="height: 428px;" class="the-slideshow gen-slider-arrows2 gen-slider-pager1 gen-slider-pager1-pos-bottom-right grid12-9  ">

	<ul class="slides">
	<?php 
		$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
		$prefix = Mage::getConfig()->getTablePrefix();
		$tblname=$prefix.'mksresponsivebannerslider';
		$sql = $connection->query("select * from $tblname where status='0'  ORDER BY imageorder ASC ");
		while($row1 = $sql->fetch())
		{
		$title = $row1["title"];
		$description = $row1["description"]; 
		$urlx = $row1["image"]; 
		$media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
		$imgurl=$media_url.$urlx;
		$url = $row1["url"]; 
	?>
		<li style="width: 100%; float: left; margin-right: -100%; position: relative; display: none;" class="slide">
			<a href="<?php echo $url; ?>">
			<img src="<?php echo $imgurl; ?>" alt="<?php echo $title; ?>" title="<?php echo $title; ?>">
			<div class="caption dark3">
			<h2><?php echo $description; ?></h2>
			</div>
			<div class="caption dark1 top-right">
			<h2></h2>
			</div>
			</a>
		</li>

	<?php } ?>
	</ul>
	 
	</div>
	</div>

	<!-- BEGIN GOOGLE ANALYTICS CODEs -->

	<script type="text/javascript">
	//<![CDATA[
	//jQuery(function($) {
	responsivemks = jQuery.noConflict(); 
	responsivemks(window).load(function(){
	responsivemks('.the-slideshow').flexslider({
	namespace:"",
	animation:'fade',
	easing:'easeInOutCirc',
	useCSS:	false,
	animationLoop:<?php echo $slide_BannerLoop; ?>,
	smoothHeight: true,
	slideshowSpeed:<?php echo ($slide_speed?$slide_speed:1000) ?>,
	animationSpeed:	600,
	pauseOnHover:<?php echo $slide_PauseOnhover; ?>
	});
	});
	//]]>
	</script>    

	<?php 
	// Module type 2 Function.......................................End
	} ?>