
<?php
$data = $this->getPaymentPaidInfo();
echo "<input type='hidden' name = 'till_current_balance' id='till_current_balance' value='" . $data['other_payment']['till_current'] . "' />";

if (count($data) > 0) {
    if (count($data) == 1) {
        foreach ($data as $other => $val) {
            if ($val['num_order_total'] == 0)
                echo "<h5 style='margin-top: 40px;margin-left: 50px;font-weight: bold;text-align: center;'> No Data </h5>";
            return;
        }
    }
    ?>
    <style>
        .dataTable-gird { height:auto;}
    </style>
    <div class="container">
    <div class="row">
        <div class="dataTable-gird">
            <table id="report_till">
                <tr>
                    <td>
                        <table class="table-bordered webpos_bordered_table">
                            <thead>
                            <th style="width:30%"><?php echo $this->__('Store'); ?></th>
                            <th style="width:30%"><?php echo $this->__('Cashier'); ?></th>
                            <th style="width:20%" class="align_right"><?php echo $this->__('From'); ?></th>
                            <th style="width:20%" class="align_right"><?php echo $this->__('To'); ?></th>    
                            </thead>
                            <tbody>
                                <tr>
                                    <td><?php echo $this->getStoreName(); ?></td>
                                    <td><?php echo Mage::getSingleton('webpos/session')->getUser()->getUsername(); ?></td>
                                    
                                    <td class="align_right"><?php echo Mage::helper('core')->formatDate($data['other_payment']['previous_time'], Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM, true); ?></td>                                    
                                    <td class="align_right"><?php echo Mage::helper('core')->formatDate(now(), Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM, true); ?></td>                                   
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="tablezreport"><table class="table-bordered webpos_bordered_table">
                            <thead>
                            <th width="80%"><?php echo $this->__('Payment Method'); ?></th>
                            <th width="10%" align="center"><?php echo $this->__('No. of Orders'); ?></th>
                            <th width="10%" align="center"><?php echo $this->__('Recorded Grand Totals'); ?></th>                            
                            </thead>
                            <tbody>
                                <?php
                                
                                foreach ($data as $payment => $info) {

                                    if ($payment == 'other_payment' && $info['money_system'] == 0) {
                                        
                                    } else {
                                        ?>
                                        <tr>
                                            <td><?php
                                                echo $info['payment_name'];
                                                if ($payment == 'cashforpos') {
                                                    echo "<br>";
                                                    echo "(<br/>".$this->__('Total').": " . Mage::helper('core')->currency($info['total'], true, false) . " ,<br/> ".$this->__('Opening Cash').": " . Mage::helper('core')->currency($info['previous_transfer'], true, false) . ",<br/> ".$this->__('Other In/Out Transactions').": " . Mage::helper('core')->currency($info['in_out'], true, false). "<br/>)";
                                                }
                                                ?></td>
                                            <td class='align_center'><?php
                                                if (isset($info['order_count']))
                                                    echo $info['order_count'];
                                                else
                                                    echo 0;
                                                ?></td>
                                            <td class="align_right"><span id="<?php echo $payment . '_money_system' ?>"><?php echo Mage::helper('core')->currency($info['money_system'], true, false); ?></span></td>                                           
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                                <tr style="border-bottom: 1px solid #0d2131;"></tr>
                                <?php $discountData = $this->getDiscountPaidInfo(); ?>

                                <tr style="border-bottom: 1px solid #0d2131;"></tr>
                                <tr class="total">
                                    <td><?php echo $this->__('Sum of Grand Totals');?></td>
                                    <td class='align_center'><span id="num_order_total" > <?php echo $data['other_payment']['num_order_total'] ?></span></td>
                                    <td class="align_right"><span id="grand_system"><?php echo Mage::helper('core')->currency($data['other_payment']['grand_order_total'], true, false); ?></span></td>                                    
                                </tr>
                                <?php /*if (Mage::getEdition() == "Enterprise") { ?>
                                    <tr class="total">
                                        <td>Vouchers</td>
                                        <td><?php echo $discountData['voucher_orders'] ?></td>
                                        <td class="align_right"><span id="discount_system"><?php
                                                if ($discountData['voucher'] < 0)
                                                    echo number_format(-$discountData['voucher'], 2, '.', '');
                                                else
                                                    echo number_format($discountData['voucher'], 2, '.', '')
                                                    ?></span> </td>                                       
                                    </tr>

                                <?php }*/ ?>
                                <tr class="total">
                                    <td><?php echo $this->__('Sum of Discounts');?></td>
                                    <td class='align_center'><?php echo $discountData['order_count'] ?></td>
                                    <td class="align_right"><span id="discount_system"><?php
                                            if ($discountData['discount_amount'] < 0)
                                                echo Mage::helper('core')->currency(-$discountData['discount_amount'], true, false);
                                            else
                                                echo Mage::helper('core')->currency($discountData['discount_amount'], true, false);
                                                ?></span> </td>                                   
                                </tr>
                                <tr class="total">
                                    <td><?php echo $this->__('Sum of Tax Amounts'); ?></td>
                                    <td class='align_center'></td>
                                    <td class="align_right"><span id="tax_system"><?php echo Mage::helper('core')->currency($data['other_payment']['tax_order_total'], true, false); ?></span></td>                                    
                                </tr>
                            </tbody>
                        </table></div>
                    </td>
                </tr>
            </table>
            <div class="action" style="margin:20px 0 0;">
                <div class="btn-print">
                <button id="print_x_report" class="scalable" ><?php echo $this->__('PRINT REPORT'); ?></button>
                </div>
            </div>
        </div>
    </div>
    </div>
<?php } ?>

<script>
    jQuery(document).ready(function () {
        jQuery('#total_value_report').html(0);
    });
    jQuery('#print_x_report').on('click', function () {
        var link = '<?php echo Mage::getUrl('webpos/payment/reportprint', array('report_type' => 'x-report', 'transfer_amout' => '0', 'diff_total' => '0')); ?>';
        window.open(link, "_blank", "scrollbars=yes, resizable=yes, width=500, height=700");
    });
    jQuery('body').on("keydown", '.manual_cal', function (event) {

        if (event.shiftKey == true) {
            // event.preventDefault(); allow to enter % char
        }

        if ((event.keyCode >= 48 && event.keyCode <= 57) ||
                (event.keyCode >= 96 && event.keyCode <= 105) ||
                event.keyCode == 16 ||
                event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 37 ||
                event.keyCode == 39 || event.keyCode == 46 || event.keyCode == 190 || event.keyCode == 110 || event.keyCode == 188) {

        } else {
            event.preventDefault();
        }

        if ((jQuery(this).val().indexOf('.') !== -1 || jQuery(this).val().indexOf(',') !== -1) && event.keyCode == 190)
            event.preventDefault();

        if ((jQuery(this).val().indexOf(',') !== -1 || jQuery(this).val().indexOf('.') !== -1) && event.keyCode == 188)
            event.preventDefault();

        if ((jQuery(this).val().indexOf(',') !== -1 || jQuery(this).val().indexOf('.') !== -1) && event.keyCode == 110)
            event.preventDefault();

    });

</script>
