<!-- shipment tracking table -->
<?php $tracking = $this->getTracking(); ?>
<?php if(is_array($tracking) && sizeof($tracking)):?>
<table width="100%" cellpadding="0" cellspacing="0" class="items" style="margin-top: 10px;">
	<thead>
		<tr><th class="header first"><?php echo $this->__('Title')?></th><th class="header"><?php echo $this->__('Number')?></th></tr>
	</thead>
	<tbody>
		<?php foreach($tracking as $_track):?>
		<tr><td><?php echo $_track->getTitle(); ?></td><td><?php echo $_track->getNumber(); ?></td></tr>
		<?php endforeach;?>
	</tbody>
</table>
<?php endif;?>