<?php    $slide_status=$this->getResponsivebannersliderEnabled();   ?>
<?php    $slide_speed=$this->getResponsivebannersliderSpeed();   ?>
<?php    $slide_type=$this->getResponsivebannerSlideType(); ?>
<?php    $slide_BannerLoop=$this->getResponsivebannerBannerLoop(); ?>
<?php    $slide_PauseOnhover=$this->getResponsivebannerPauseOnhover(); ?>


<?php
// Module Enable/Dsable Function.......................................
if($slide_status==1){ ?>



<?php
// Module type Function.......................................
if($slide_type=='1'){ ?>  
	<?php  $cssurl =  str_replace('index.php/','',$this->getUrl());?>  
	<div class="home-banner flexslider"> 
		<ul class="slides">
		<?php 
			$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
			$prefix = Mage::getConfig()->getTablePrefix();
			$tblname=$prefix.'mksresponsivebannerslider';
			$sql = $connection->query("select * from $tblname where status='0' and groupname='home_banner' ORDER BY imageorder ASC ");
			while($row1 = $sql->fetch())
			{
			$title = $row1["title"];
			$description = $row1["description"];
			$urlx = $row1["image"]; 
			$media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
			$imgurl=$media_url.$urlx;
			$url = empty($row1["url"])?"#":$row1["url"]; 
		?>
			<li data-thumb="<?php echo $imgurl; ?>">
			 	<a href="<?php echo $url; ?>" >
			 		<img src="<?php echo $imgurl; ?>">
			 	</a>
			</li>

		<?php } ?>
		</ul> 
	</div>

	<!-- BEGIN GOOGLE ANALYTICS CODEs -->

	<script type="text/javascript">
	//<![CDATA[
	//jQuery(function($) {
	responsivemks = jQuery.noConflict(); 
	responsivemks(window).load(function(){
		responsivemks('.home-banner').flexslider({
		    animation: "slide",
		    controlNav: "thumbanails",
		    directionNav:false,
		    touch:true,
		    smoothHeight: true
		}); 
	});  
	//]]>
	</script>    

	<?php 
	// Module type 2 Function.......................................End
	} ?>

	<?php } else { ?>

<h1 style="color:red;">Enable ( Responsive banner ) Module via Admin = System -> Configuration-> MKS RESPONSIVE BANNER-> General Setting </h1>

 <?php } ?>