<?php    $slide_status=$this->getResponsivebannersliderEnabled();   ?>
<?php    $slide_speed=$this->getResponsivebannersliderSpeed();   ?>
<?php    $slide_type=$this->getResponsivebannerSlideType(); ?>
<?php    $slide_BannerLoop=$this->getResponsivebannerBannerLoop(); ?>
<?php    $slide_PauseOnhover=$this->getResponsivebannerPauseOnhover(); ?>


<?php
// Module Enable/Dsable Function.......................................
if($slide_status==1){ ?> 
<?php
// Module type Function.......................................
if($slide_type=='1'){ ?>  
	<?php  $cssurl =  str_replace('index.php/','',$this->getUrl());?>  
	<section class="keyles-entry">
		<div class="keyles-entry-slider flexslider"> 
			<ul class="slides">
			<?php 
				$connection = Mage::getSingleton('core/resource')->getConnection('core_write');
				$prefix = Mage::getConfig()->getTablePrefix();
				$tblname=$prefix.'mksresponsivebannerslider';
				$sql = $connection->query("select * from $tblname where status='0' and groupname='keyless_entry' ORDER BY imageorder ASC ");
				while($row1 = $sql->fetch())
				{
				$title = $row1["title"];
				$description = $row1["description"];
				$urlx = $row1["image"]; 
				$media_url =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
				$imgurl=$media_url.$urlx;
				$url = empty($row1["url"])?"#":$row1["url"]; 
			?>
				<li data-thumb="<?php echo $imgurl; ?>"> 
			 		<a href="<?php echo $url ?>"><img src="<?php echo $imgurl; ?>"></a>
			 		<div class="flex-caption container">
			 			<!--<h2><?php echo $title; ?></h2>-->
			 			<p class="hidden-xs hidden-sm"><?php echo $description?></p>
			 			<!--<a href="<?php echo $url ?>" class="button">Shop Now</a>-->
			 		</div> 
				</li>

			<?php } ?>
			</ul> 
		</div>
	</section>
	<!-- BEGIN GOOGLE ANALYTICS CODEs -->

	<script type="text/javascript">
	//<![CDATA[
	//jQuery(function($) {
	responsivemks = jQuery.noConflict(); 
	responsivemks(window).load(function(){
		responsivemks('.keyles-entry-slider').flexslider({
		    animation: "slide",
		    controlNav: false,
		    directionNav:true,
		    touch:true,
		    smoothHeight: true,
		    minItems:1,
		    maxItems:1
		}); 
	});  
	//]]>
	</script>    

	<?php 
	// Module type 2 Function.......................................End
	} ?>

	<?php } else { ?>

<h1 style="color:red;">Enable ( Responsive banner ) Module via Admin = System -> Configuration-> MKS RESPONSIVE BANNER-> General Setting </h1>

 <?php } ?>